from rclpy.node import Node

from kokoro import KPipeline
import numpy as np
import torch
import soundfile as sf
import io
from typing import Tuple
from sobits_tts.include._base_tts import BaseTTSModel

class KokoroTTSModel(BaseTTSModel):
    def __init__(self, node: Node, sample_rate: int):
        super().__init__(node, sample_rate) 

        # Kokoro TTS 固有のROSパラメータをここで宣言・取得
        self._node.declare_parameter('kokoro.lang_code', 'a')
        self._node.declare_parameter('kokoro.voice', 'af_heart')
        self._node.declare_parameter('kokoro.speech_speed', 1.0)
        self._node.declare_parameter('kokoro.split_regex', r'[\n,.!?、。！？]+')

        self.lang_code = self._node.get_parameter('kokoro.lang_code').get_parameter_value().string_value
        self.voice = self._node.get_parameter('kokoro.voice').get_parameter_value().string_value
        self.speech_speed = self._node.get_parameter('kokoro.speech_speed').get_parameter_value().double_value
        self.split_regex = self._node.get_parameter('kokoro.split_regex').get_parameter_value().string_value

        self.device = "cuda:0" if torch.cuda.is_available() else "cpu"
        self._logger.debug(f"KokoroTTS using device: {self.device}")

        try:
            self.pipeline = KPipeline(lang_code=self.lang_code, device=self.device)
            self._logger.info(f"Kokoro TTS initialized (Lang: {self.lang_code}, Voice: {self.voice})")
        except Exception as e:
            self._logger.error(f"Failed to initialize Kokoro TTS: {e}")
            raise 

    def generate_audio(self, text: str) -> Tuple[float, io.BytesIO]:
        combined_audio_chunks = []
        total_samples = 0

        try:
            for i, result in enumerate(self.pipeline(text, voice=self.voice, speed=self.speech_speed, split_pattern=self.split_regex)):
                audio_chunk = result.audio

                if isinstance(audio_chunk, torch.Tensor):
                    audio_chunk = audio_chunk.cpu().numpy()
                if audio_chunk.ndim == 1:
                    final_chunk = audio_chunk
                else:
                    self._logger.error(f"Unsupported audio chunk shape.")
                    return 0.0, None

                combined_audio_chunks.append(final_chunk) # 処理済みチャンクを追加
                total_samples += final_chunk.shape[0] # 総サンプル数を加算
            
        except RuntimeError as e:
            self._logger.error(f"Runtime error during Kokoro KPipeline processing: {e}", exc_info=True)
            return 0.0, None
        except Exception as e:
            self._logger.error(f"An unexpected error occurred during Kokoro audio generation: {e}", exc_info=True)
            return 0.0, None

        # 音声チャンクが何も生成されなかった場合
        if not combined_audio_chunks:
            self._logger.warn("No audio chunks generated by Kokoro TTS for the given text.")
            return 0.0, None

        try:
            # すべての音声チャンクを結合
            combined_audio = np.concatenate(combined_audio_chunks, axis=0)
        except ValueError as e:
             self._logger.error(f"Error concatenating audio chunks in KokoroTTSModel: {e}. Shapes: {[ch.shape for ch in combined_audio_chunks]}", exc_info=True)
             return 0.0, None

        # 推定再生時間の計算
        play_time = float(total_samples) / self._sample_rate

        # 再生時間が無効な場合
        if play_time <= 0:
            self._logger.warn(f"Kokoro: Calculated play_time is zero or negative ({play_time:.2f}s).")
            return 0.0, None

        try:
            buffer = io.BytesIO()
            sf.write(buffer, combined_audio, self._sample_rate, format='WAV', subtype='PCM_16')
            buffer.seek(0)
            return play_time, buffer
        except Exception as e:
            self._logger.error(f"Error writing audio to buffer in KokoroTTSModel: {e}", exc_info=True)
            return 0.0, None